// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHiWm7_d3h8YeeHejYM_9jF0k2rPJXqoQ',
    appId: '1:859504170418:web:e91a98e7319a79a9e900ab',
    messagingSenderId: '859504170418',
    projectId: 'aquaping-697b8',
    authDomain: 'aquaping-697b8.firebaseapp.com',
    storageBucket: 'aquaping-697b8.firebasestorage.app',
    measurementId: 'G-C9L4LSGKS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6yN9UqCwzbgwXDrbnOu-ZDyK0GqPhW5g',
    appId: '1:859504170418:android:1c9266ee8336b7c3e900ab',
    messagingSenderId: '859504170418',
    projectId: 'aquaping-697b8',
    storageBucket: 'aquaping-697b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCpMGW3DktXzkwWtsJA77_PqOS0-Unjj0',
    appId: '1:859504170418:ios:b9f4aad9836a6b14e900ab',
    messagingSenderId: '859504170418',
    projectId: 'aquaping-697b8',
    storageBucket: 'aquaping-697b8.firebasestorage.app',
    iosBundleId: 'com.example.aquapingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCpMGW3DktXzkwWtsJA77_PqOS0-Unjj0',
    appId: '1:859504170418:ios:b9f4aad9836a6b14e900ab',
    messagingSenderId: '859504170418',
    projectId: 'aquaping-697b8',
    storageBucket: 'aquaping-697b8.firebasestorage.app',
    iosBundleId: 'com.example.aquapingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHiWm7_d3h8YeeHejYM_9jF0k2rPJXqoQ',
    appId: '1:859504170418:web:4b4481b61bb414ace900ab',
    messagingSenderId: '859504170418',
    projectId: 'aquaping-697b8',
    authDomain: 'aquaping-697b8.firebaseapp.com',
    storageBucket: 'aquaping-697b8.firebasestorage.app',
    measurementId: 'G-VYWTLPXMBC',
  );

}